name: techne
favicon: null
layout_spectrum: 0.5329304202459753
typography_spectrum: 0.7886788018513471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7904670762363821
  lightness: 0.3245136502664536
  saturation: 0.10874186991713941
  rhythmicContrast: 0.5656643118709326
purpose: []
